cmake_minimum_required(VERSION 3.22.1)
project(LuoGu)

set(CMAKE_CXX_STANDARD 17)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O0")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0")
add_executable(P8218 "Algorithm 2-1/P8218.cpp")
add_executable(P1719 "Algorithm 2-1/P1719.cpp")
add_executable(P1314 "Algorithm 2-1/P1314.cpp")
add_executable(P2367 "Algorithm 2-1/P2367.cpp")
add_executable(P3397 "Algorithm 2-1/P3397.cpp")
add_executable(P1496 "Algorithm 2-1/P1496.cpp")
add_executable(P1955 "Algorithm 2-1/P1955.cpp")
add_executable(P1884 "Algorithm 2-1/P1884.cpp")
add_executable(P2004 "Algorithm 2-1/P2004.cpp")
add_executable(P3017 "Algorithm 2-1/P3017.cpp")
add_executable(P1904 "Algorithm 2-1/P1904.cpp")
add_executable(P2882 "Algorithm 2-1/P2882.cpp")
add_executable(P4552 "Algorithm 2-1/P4552.cpp")
add_executable(P3029 "Algorithm 2-1/P3029.cpp")
add_executable(P1102 "Algorithm 2-2/P1102.cpp")
add_executable(P1638 "Algorithm 2-2/P1638.cpp")
add_executable(P1115 "Algorithm 2-2/P1115.cpp")
add_executable(P7072 "Algorithm 2-2/P7072.cpp")
add_executable(P4147 "Algorithm 2-2/P4147.cpp")
add_executable(P2866 "Algorithm 2-2/P2866.cpp")
add_executable(P1950 "Algorithm 2-2/P1950.cpp")
add_executable(P2032 "Algorithm 2-2/P2032.cpp")
add_executable(P2216 "Algorithm 2-2/P2216.cpp")
add_executable(UVA11572 "Algorithm 2-2/UVA11572.cpp")
add_executable(P1886 "Algorithm 2-2/P1886.cpp")
add_executable(P3467 "Algorithm 2-2/P3467.cpp")
add_executable(P2880 "Algorithm 2-2/P2880.cpp")
add_executable(P1177 "Algorithm 2-3/P1177.cpp")
add_executable(P1908 "Algorithm 2-3/P1908.cpp")
add_executable(P1966 "Algorithm 2-3/P1966.cpp")
add_executable(P1226 "Algorithm 2-3/P1226.cpp")
add_executable(P2415 "Algorithm 2-3/P2415.cpp")
add_executable(P1257 "Algorithm 2-3/P1257.cpp")
add_executable(P1228 "Algorithm 2-3/P1228.cpp")
add_executable(P2345 "Algorithm 2-3/P2345.cpp")
